### ISSUE TITLE
random ?

### ISSUE THREAD

**Issue by Noname400** [kanhavishva/PubHunt#5]
you wrote that the search is in random mode. but I see that there is a bust.
from 29 bits (now I have 44 bits)
or I don't understand how the program works
can you explain

**Comment by kanhavishva** [comment]
Randomize() function generate random values in inputKey variable, because we are generating public keys so it needs to be 256 bit, means 4 times 64 bit space for each key:


![image](https://user-images.githubusercontent.com/24961687/123517464-b2649a80-d6be-11eb-98ec-a87837de4f73.png)


Then we feed this data into GPU kernel, here we are gets two hash160 (ripemd160(sha256(compressed-pubkey))) for each key by adding 02, 03 for compressed keys.

Note: program doesn't verify for public key validation.

![image](https://user-images.githubusercontent.com/24961687/123517477-d0ca9600-d6be-11eb-8f49-611b47d8adac.png)

Then it check for match in given hash160 list, one by one, if it find any match, then it will increase found counter and push pubkey and hash160 to variable found.

![image](https://user-images.githubusercontent.com/24961687/123517673-f99f5b00-d6bf-11eb-93c9-fdac96a98ec3.png)

**Comment by kanhavishva** [comment]
This program is just a fun part, because it is not possible to find anything in 256 bit space by brute-forcing.
